version: "3.6"
networks:
  frontend:
  backend:
services:
  db:
    image: postgres:12
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "cdefense"]
      interval: 30s
      timeout: 3s

